// src/views/SettingsPage.vue
<script setup>
import { ref, onMounted, computed, watch } from 'vue'
import axios from 'axios'
import { ElMessage, ElMessageBox } from 'element-plus'

const sboxNames = ref([])
const selectedName = ref('')
const currentName = ref('')
const currentContent = ref('')
const isStandard = ref(false)
const isExpanded = ref(true)
const isAppearanceExpanded = ref(true)

// Appearance Settings
const terminalWallpaper = ref('')
const terminalOpacity = ref(0.3)
const wallpaperPreview = ref('')

// Parse currentContent into 16x16 grid
const sboxGrid = computed(() => {
    try {
        let clean = currentContent.value.replace(/[\[\]\s]/g, '')
        if (clean.includes(',')) {
            // JSON format
            return currentContent.value.replace(/[\[\]]/g, '').split(',').map(v => v.trim()).filter(v => v !== '')
        } else {
            // Hex stream
            let bytes = []
            for (let i = 0; i < clean.length; i += 2) {
                bytes.push(clean.substring(i, i + 2))
            }
            return bytes
        }
    } catch (e) { return [] }
})

const loadSboxNames = async (retries = 5) => {
    try {
        const response = await axios.get('http://127.0.0.1:3335/api/sbox/names')
        sboxNames.value = response.data.names
        if (sboxNames.value.length > 0 && !selectedName.value) {
            selectSbox(sboxNames.value[0])
        }
    } catch (error) { 
        console.error("Load SBox Names failed, retrying...", error)
        if (retries > 0) {
            setTimeout(() => loadSboxNames(retries - 1), 500)
        }
    }
}

const selectSbox = async (name) => {
    selectedName.value = name
    try {
        const response = await axios.get(`http://127.0.0.1:3335/api/sbox/get/${encodeURIComponent(name)}`)
        currentName.value = response.data.name
        currentContent.value = response.data.content
        isStandard.value = response.data.is_standard
    } catch (error) {
        ElMessage.error("Failed to load S-box")
    }
}

const newSbox = () => {
    selectedName.value = ''
    currentName.value = 'New S-Box'
    currentContent.value = ''
    isStandard.value = false
}

const cloneSbox = () => {
    const originalName = currentName.value
    selectedName.value = ''
    currentName.value = originalName + '_Copy'
    isStandard.value = false
    ElMessage.success("已克隆配置")
}

const saveSbox = async () => {
    if (!currentName.value) return ElMessage.warning("名称不能为空")
    try {
        await axios.post('http://127.0.0.1:3335/api/sbox/save', {
            name: currentName.value,
            content: currentContent.value
        })
        ElMessage.success("保存成功")
        await loadSboxNames()
        selectSbox(currentName.value)
    } catch (error) {
        ElMessage.error("保存失败: " + (error.response?.data?.detail || error.message))
    }
}

const deleteSbox = async () => {
    if (isStandard.value) return
    
    try {
        await ElMessageBox.confirm(`确定要删除 ${selectedName.value} 吗?`, '警告', {
            confirmButtonText: '确定删除',
            cancelButtonText: '取消',
            type: 'warning'
        })
        
        await axios.delete(`http://127.0.0.1:3335/api/sbox/delete/${encodeURIComponent(selectedName.value)}`)
        ElMessage.success("删除成功")
        await loadSboxNames()
        if (sboxNames.value.length > 0) selectSbox(sboxNames.value[0])
    } catch (error) {
        if (error !== 'cancel') {
             ElMessage.error("删除失败")
        }
    }
}

// --- Appearance Functions ---
const handleWallpaperUpload = (file) => {
    const reader = new FileReader()
    reader.onload = (e) => {
        const result = e.target.result
        // Basic size check (5MB limit)
        if (result.length > 5 * 1024 * 1024 * 1.37) { // Base64 is ~37% larger
             ElMessage.error('图片大小不能超过 5MB')
             return
        }
        terminalWallpaper.value = result
        wallpaperPreview.value = result
        saveAppearanceSettings()
    }
    reader.readAsDataURL(file.raw)
    return false
}

const removeWallpaper = () => {
    terminalWallpaper.value = ''
    wallpaperPreview.value = ''
    saveAppearanceSettings()
}

const saveAppearanceSettings = () => {
    try {
        localStorage.setItem('terminal_bg_image', terminalWallpaper.value)
        localStorage.setItem('terminal_bg_opacity', terminalOpacity.value)
        // Dispatch event for other tabs/components
        window.dispatchEvent(new Event('storage'))
        ElMessage.success('外观设置已保存')
    } catch (e) {
        console.error("Save settings failed:", e)
        if (e.name === 'QuotaExceededError') {
             ElMessage.error('保存失败：图片太大超过了存储限制，请使用更小的图片')
        } else {
             ElMessage.error('保存设置失败')
        }
    }
}

const loadAppearanceSettings = () => {
    const bg = localStorage.getItem('terminal_bg_image')
    const opacity = localStorage.getItem('terminal_bg_opacity')
    
    if (bg) {
        terminalWallpaper.value = bg
        wallpaperPreview.value = bg
    }
    
    if (opacity !== null) {
        terminalOpacity.value = parseFloat(opacity)
    }
}

onMounted(() => {
    loadSboxNames()
    loadAppearanceSettings()
})
</script>

<template>
    <div class="page-container">
        <h1>设置</h1>
        
        <el-card class="section-card" :body-style="{ padding: '0px' }">
            <template #header>
                <div class="section-header" @click="isExpanded = !isExpanded">
                    <div class="header-left">
                        <h2>配置 S盒 (S-Box Configuration)</h2>
                        <el-tag v-if="isStandard" type="success" size="small" effect="dark" round>标准 (Static)</el-tag>
                        <el-tag v-else type="primary" size="small" effect="dark" round>自定义 (Custom)</el-tag>
                    </div>
                    <el-icon class="expand-icon" :style="{ transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }">
                         <ArrowDown />
                    </el-icon>
                </div>
            </template>

            <div class="sbox-editor-wrapper" :class="{ collapsed: !isExpanded }">
                <div class="sbox-editor">
                    <!-- Sidebar -->
                    <div class="side-list">
                        <div class="list-container">
                            <div 
                                v-for="name in sboxNames" 
                                :key="name" 
                                class="list-item"
                                :class="{ active: selectedName === name, is_standard: name.startsWith('Standard') }"
                                @click="selectSbox(name)"
                            >
                                <span class="dot"></span>
                                {{ name }}
                            </div>
                        </div>
                        <el-button class="add-btn" @click="newSbox" plain type="primary" size="small" style="width: 100%; margin-top: 10px;">
                            <el-icon><Plus /></el-icon> 新建 S盒
                        </el-button>
                    </div>

                    <!-- Main Panel -->
                    <div class="editor-main">
                        <div class="form-header">
                            <div class="form-group name-group">
                                <span class="input-label">配置名称:</span>
                                <el-input v-model="currentName" :readonly="isStandard" placeholder="输入S盒名称">
                                    <template #append v-if="!isStandard">
                                        <el-button @click="saveSbox">保存</el-button>
                                    </template>
                                </el-input>
                            </div>
                             <el-button @click="cloneSbox" size="small">
                                <el-icon><CopyDocument /></el-icon> 克隆
                            </el-button>
                        </div>

                        <!-- Visualization Grid -->
                        <div class="visualization">
                            <span class="input-label">矩阵视图 (16x16 Grid):</span>
                            <div class="grid-container">
                                <div v-for="(val, idx) in sboxGrid" :key="idx" class="grid-cell" :title="`Index: ${idx}`">
                                    {{ val.length === 2 ? val : ('0' + val).slice(-2) }}
                                </div>
                            </div>
                        </div>

                        <div class="form-group flex-grow">
                             <span class="input-label">原始数据 (Hex Stream):</span>
                             <el-input 
                                v-model="currentContent" 
                                :readonly="isStandard" 
                                type="textarea" 
                                :rows="4"
                                resize="none"
                                placeholder="例如: d690e9fe..."
                             />
                        </div>

                        <div class="actions">
                             <el-alert
                                v-if="isStandard"
                                title="标准S盒不可直接修改，请克隆后编辑"
                                type="warning"
                                show-icon
                                :closable="false"
                                style="width: 100%"
                            />
                            <div v-else style="display: flex; gap: 10px; width: 100%;">
                                <el-button type="primary" @click="saveSbox" style="flex: 1">保存配置</el-button>
                                <el-button type="danger" plain @click="deleteSbox">删除此配置</el-button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </el-card>



        <el-card class="section-card" :body-style="{ padding: '0px' }">
            <template #header>
                <div class="section-header" @click="isAppearanceExpanded = !isAppearanceExpanded">
                    <div class="header-left">
                        <h2>终端外观 (Terminal Appearance)</h2>
                    </div>
                    <el-icon class="expand-icon" :style="{ transform: isAppearanceExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }">
                         <ArrowDown />
                    </el-icon>
                </div>
            </template>

            <div class="sbox-editor-wrapper" :class="{ collapsed: !isAppearanceExpanded }">
                <div class="appearance-editor">
                    <div class="setting-item">
                        <div class="setting-label">背景图片 (Wallpaper)</div>
                        <div class="wallpaper-upload">
                             <el-upload
                                class="avatar-uploader"
                                :show-file-list="false"
                                :auto-upload="false"
                                :on-change="handleWallpaperUpload"
                                accept="image/*"
                            >
                                <img v-if="wallpaperPreview" :src="wallpaperPreview" class="avatar" />
                                <el-icon v-else class="avatar-uploader-icon"><Plus /></el-icon>
                            </el-upload>
                            <div class="upload-hint">
                                <p>点击上传图片 (最大 5MB)</p>
                                <el-button v-if="wallpaperPreview" type="danger" link @click.stop="removeWallpaper">清除壁纸</el-button>
                            </div>
                        </div>
                    </div>

                    <div class="setting-item">
                        <div class="setting-label">
                            背景不透明度 (Opacity)
                            <span class="value-text">{{ Math.round(terminalOpacity * 100) }}%</span>
                        </div>
                        <div class="slider-container">
                             <el-slider 
                                v-model="terminalOpacity" 
                                :min="0" 
                                :max="1" 
                                :step="0.05" 
                                show-input
                                @change="saveAppearanceSettings"
                             />
                        </div>
                    </div>
                </div>
            </div>
        </el-card>

        <div class="about-section">
            <el-card class="about-card">
                <template #header>
                    <div class="about-header">
                         <h2>关于 Descrypt Pro</h2>
                    </div>
                </template>
                <p>由于不会写解密脚本于是用AI搓了一个奇怪小玩意。受 CyberChef 启发，基于 Electron 和 FastAPI 构建。</p>
                <el-descriptions :column="3" border>
                    <el-descriptions-item label="版本">0.0.1</el-descriptions-item>
                    <el-descriptions-item label="驱动">QAQ</el-descriptions-item>
                    <el-descriptions-item label="状态">
                         <el-tag type="success">运行中</el-tag>
                    </el-descriptions-item>
                </el-descriptions>
            </el-card>
        </div>
    </div>
</template>

<style scoped>
.page-container {
    padding: 24px 0;
}

h1 {
    margin-bottom: 24px;
    font-size: 24px;
    color: var(--text-color);
}

.section-card {
    background-color: var(--panel-bg);
    border-color: var(--border-color);
    margin-bottom: 24px;
    transition: all 0.3s ease;
}

.section-card:hover {
    box-shadow: 0 0 15px var(--accent-color);
    border-color: var(--accent-color);
}

.section-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    cursor: pointer;
}

.header-left {
    display: flex;
    align-items: center;
    gap: 12px;
}

.section-header h2 {
    margin: 0;
    font-size: 16px;
    color: var(--text-color);
}

.expand-icon {
    font-size: 16px;
    color: var(--text-color);
    transition: transform 0.3s;
}

.sbox-editor-wrapper {
    overflow: hidden;
    max-height: 800px;
    transition: max-height 0.4s cubic-bezier(0.645, 0.045, 0.355, 1);
}

.sbox-editor-wrapper.collapsed {
    max-height: 0;
}

.sbox-editor {
    display: flex;
    height: 600px;
}

.side-list {
    width: 220px;
    border-right: 1px solid var(--border-color);
    display: flex;
    flex-direction: column;
    padding: 12px;
    background: var(--input-bg);
}

.list-container {
    flex: 1;
    overflow-y: auto;
}

.list-item {
    padding: 10px 12px;
    border-radius: 4px;
    cursor: pointer;
    margin-bottom: 4px;
    color: var(--text-color);
    transition: all 0.2s;
    font-size: 13px;
    display: flex;
    align-items: center;
    gap: 8px;
}

.list-item .dot {
    width: 6px;
    height: 6px;
    border-radius: 50%;
    background: #666;
}

.list-item.is_standard .dot {
    background: var(--el-color-success);
}

.list-item:hover {
    background: var(--hover-bg);
}

.list-item.active {
    background: var(--el-color-primary-light-9);
    color: var(--el-color-primary);
}

.list-item.active .dot {
    background: var(--el-color-primary);
}

:global(.dark) .list-item.active {
    background: var(--el-color-primary-dark-2);
}

.editor-main {
    flex: 1;
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 20px;
}

.form-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
    gap: 20px;
}

.name-group {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.input-label {
    font-size: 12px;
    color: var(--el-text-color-secondary);
    font-weight: bold;
}

.visualization {
    display: flex;
    flex-direction: column;
    gap: 8px;
    flex: 1;
    min-height: 0;
}

.grid-container {
    display: grid;
    grid-template-columns: repeat(16, 1fr);
    gap: 2px;
    background: var(--el-fill-color-dark);
    padding: 4px;
    border-radius: 4px;
    border: 1px solid var(--border-color);
    overflow-y: auto;
    max-height: 300px;
}

:global(.dark) .grid-container {
    background: #151217; /* Darker shade of bg #1C191F */
    border-color: var(--border-color);
}

.grid-cell {
    aspect-ratio: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 10px;
    background: var(--el-bg-color);
    color: var(--text-color);
    cursor: default;
}

:global(.dark) .grid-cell {
    background: #2B2530; /* panel-bg */
    color: var(--text-color);
}

.grid-cell:hover {
    background: var(--el-color-primary);
    color: #fff;
}

.form-group {
    display: flex;
    flex-direction: column;
    gap: 8px;
}

.flex-grow {
    flex: 1;
}

.about-card {
    background: var(--panel-bg);
    border-color: var(--border-color);
}

.appearance-editor {
    padding: 24px;
    display: flex;
    flex-direction: column;
    gap: 32px;
}

.setting-item {
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.setting-label {
    font-size: 14px;
    font-weight: 600;
    color: var(--text-color);
    display: flex;
    justify-content: space-between;
}

.value-text {
    color: var(--el-color-primary);
}

.wallpaper-upload {
    display: flex;
    gap: 20px;
    align-items: center;
}

.avatar-uploader {
    border: 1px dashed var(--border-color);
    border-radius: 6px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
    transition: var(--el-transition-duration-fast);
    width: 120px;
    height: 120px;
    display: flex;
    align-items: center;
    justify-content: center;
}

.avatar-uploader:hover {
    border-color: var(--el-color-primary);
}

.avatar-uploader-icon {
    font-size: 28px;
    color: #8c939d;
    width: 120px;
    height: 120px;
    text-align: center;
    display: flex;
    align-items: center;
    justify-content: center;
}

.avatar {
    width: 120px;
    height: 120px;
    display: block;
    object-fit: cover;
}

.upload-hint {
    font-size: 12px;
    color: var(--el-text-color-secondary);
}

.slider-container {
    padding: 0 12px;
}
</style>

// front/src/app/components/SettingsPage.tsx
import { useState, useEffect } from 'react';
import { ChevronDown, Palette, Database, Check, Plus, Copy, Trash2, Upload, X, Info } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { getSBoxNames, getSBox, saveSBox, deleteSBox } from '@/app/api';

interface SettingItem {
  id: string;
  title: string;
  icon: any;
  content: React.ReactNode;
}

export function SettingsPage() {
  const [expandedId, setExpandedId] = useState<string | null>('sbox');

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  const settings: SettingItem[] = [
    { id: 'sbox', title: 'S-Box 配置', icon: Database, content: <SBoxSettings /> },
    { id: 'theme', title: '主题设置', icon: Palette, content: <ThemeSettings /> },
    { id: 'about', title: '关于', icon: Info, content: <AboutSection /> },
  ];

  return (
    <div className="max-w-4xl mx-auto">
      <div className="mb-12 relative">
        <div className="inline-flex items-center gap-3 px-6 py-3 bg-gradient-to-r from-gray-500/10 via-slate-500/10 to-gray-500/10 rounded-full border border-gray-200/50 backdrop-blur-sm">
          <div className="w-2 h-2 rounded-full bg-gray-500 animate-pulse"></div>
          <h1 className="text-3xl text-transparent bg-clip-text bg-gradient-to-r from-gray-600 to-slate-600">设置</h1>
        </div>
        <p className="mt-4 text-gray-500 ml-6">个性化您的工具箱</p>
      </div>

      <div className="space-y-4">
        {settings.map((item) => {
          const Icon = item.icon;
          const isExpanded = expandedId === item.id;

          return (
            <div
              key={item.id}
              className="bg-white/50 backdrop-blur-md rounded-2xl ring-1 ring-gray-200 overflow-hidden transition-all duration-300"
            >
              <button
                onClick={() => toggleExpand(item.id)}
                className="w-full p-6 flex items-center justify-between hover:bg-white/70 transition-all duration-300 group"
              >
                <div className="flex items-center gap-4">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-gray-400 to-slate-500 flex items-center justify-center shadow-md group-hover:scale-110 transition-transform duration-300">
                    <Icon className="w-5 h-5 text-white" strokeWidth={2.5} />
                  </div>
                  <span className="text-lg text-gray-700 group-hover:text-gray-900 transition-colors">
                    {item.title}
                  </span>
                </div>
                <motion.div
                  animate={{ rotate: isExpanded ? 180 : 0 }}
                  transition={{ duration: 0.3, ease: 'easeInOut' }}
                >
                  <ChevronDown className="w-5 h-5 text-gray-400 group-hover:text-gray-600 transition-colors" />
                </motion.div>
              </button>

              <AnimatePresence initial={false}>
                {isExpanded && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.4, ease: [0.4, 0, 0.2, 1], opacity: { duration: 0.25 } }}
                  >
                    <div className="px-6 pb-6 border-t border-gray-200">
                      <motion.div
                        initial={{ y: -10 }}
                        animate={{ y: 0 }}
                        transition={{ duration: 0.3, delay: 0.1 }}
                      >
                        {item.content}
                      </motion.div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          );
        })}
      </div>
    </div>
  );
}

function SBoxSettings() {
  const [sboxNames, setSboxNames] = useState<string[]>([]);
  const [selectedName, setSelectedName] = useState('');
  const [currentContent, setCurrentContent] = useState('');
  const [currentName, setCurrentName] = useState('');
  const [isStandard, setIsStandard] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadNames();
  }, []);

  const loadNames = async () => {
    try {
      const names = await getSBoxNames();
      setSboxNames(names);
      if (names.length > 0) {
        selectSbox(names[0]);
      }
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const selectSbox = async (name: string) => {
    setSelectedName(name);
    try {
      const data = await getSBox(name);
      setCurrentName(data.name);
      setCurrentContent(data.content);
      setIsStandard(data.is_standard);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleSave = async () => {
    if (!currentName.trim()) return;
    try {
      await saveSBox(currentName, currentContent);
      await loadNames();
      setSelectedName(currentName);
      setError(null);
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleDelete = async () => {
    if (isStandard || !confirm('确定删除此 S-Box?')) return;
    try {
      await deleteSBox(selectedName);
      await loadNames();
    } catch (e: any) {
      setError(e.message);
    }
  };

  const handleClone = () => {
    setCurrentName(currentName + '_Copy');
    setIsStandard(false);
  };

  const handleNew = () => {
    setSelectedName('');
    setCurrentName('New S-Box');
    setCurrentContent('');
    setIsStandard(false);
  };

  // Parse content to 16x16 grid
  const sboxGrid = (() => {
    try {
      const clean = currentContent.replace(/[\[\]\s]/g, '');
      if (clean.includes(',')) {
        return currentContent.replace(/[\[\]]/g, '').split(',').map(v => v.trim()).filter(v => v !== '');
      }
      const bytes = [];
      for (let i = 0; i < clean.length; i += 2) {
        bytes.push(clean.substring(i, i + 2));
      }
      return bytes;
    } catch { return []; }
  })();

  if (loading) return <div className="pt-6 text-center text-gray-500">加载中...</div>;

  return (
    <div className="pt-6 space-y-4">
      {error && <div className="text-sm text-red-500 bg-red-50 px-3 py-2 rounded-lg">{error}</div>}

      <div className="flex gap-4">
        {/* S-Box List */}
        <div className="w-48 space-y-2">
          {sboxNames.map(name => (
            <button
              key={name}
              onClick={() => selectSbox(name)}
              className={`w-full text-left px-3 py-2 rounded-lg text-sm transition-all ${selectedName === name
                ? 'bg-purple-500 text-white'
                : 'bg-white/60 hover:bg-white hover:shadow-sm'
                }`}
            >
              {name}
            </button>
          ))}
          <button onClick={handleNew} className="w-full px-3 py-2 rounded-lg text-sm bg-purple-100 text-purple-700 hover:bg-purple-200 transition-all flex items-center gap-2">
            <Plus className="w-4 h-4" /> 新建
          </button>
        </div>

        {/* S-Box Editor */}
        <div className="flex-1 space-y-4">
          <div className="flex gap-3">
            <input
              type="text"
              value={currentName}
              onChange={(e) => setCurrentName(e.target.value)}
              disabled={isStandard}
              placeholder="S-Box 名称"
              className="flex-1 px-3 py-2 bg-white/60 border border-gray-200 rounded-lg text-sm disabled:opacity-50"
            />
            <button onClick={handleClone} className="px-3 py-2 bg-white/60 border border-gray-200 rounded-lg text-sm hover:bg-white transition-all flex items-center gap-1">
              <Copy className="w-4 h-4" /> 克隆
            </button>
          </div>

          {/* 16x16 Grid Preview */}
          {sboxGrid.length > 0 && (
            <div className="grid grid-cols-16 gap-0.5 p-2 bg-gray-100 rounded-lg max-h-48 overflow-auto">
              {sboxGrid.map((val, idx) => (
                <div key={idx} className="w-5 h-5 flex items-center justify-center text-[8px] bg-white hover:bg-purple-100 transition-colors" title={`Index: ${idx}`}>
                  {val.length === 2 ? val : ('0' + val).slice(-2)}
                </div>
              ))}
            </div>
          )}

          <textarea
            value={currentContent}
            onChange={(e) => setCurrentContent(e.target.value)}
            disabled={isStandard}
            placeholder="Hex 数据 (256字节)..."
            className="w-full h-24 px-3 py-2 bg-white/60 border border-gray-200 rounded-lg text-xs font-mono disabled:opacity-50 resize-none"
          />

          {isStandard ? (
            <div className="text-sm text-amber-600 bg-amber-50 px-3 py-2 rounded-lg">
              标准 S-Box 不可修改，请克隆后编辑
            </div>
          ) : (
            <div className="flex gap-3">
              <button onClick={handleSave} className="flex-1 px-4 py-2 rounded-lg bg-purple-500 text-white hover:bg-purple-600 transition-all">
                保存
              </button>
              <button onClick={handleDelete} className="px-4 py-2 rounded-lg bg-red-100 text-red-600 hover:bg-red-200 transition-all flex items-center gap-1">
                <Trash2 className="w-4 h-4" /> 删除
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function ThemeSettings() {
  const [wallpaper, setWallpaper] = useState('');
  const [opacity, setOpacity] = useState(0.3);

  useEffect(() => {
    const savedWallpaper = localStorage.getItem('terminal_bg_image') || '';
    const savedOpacity = localStorage.getItem('terminal_bg_opacity');
    setWallpaper(savedWallpaper);
    if (savedOpacity) setOpacity(parseFloat(savedOpacity));
  }, []);

  const handleUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > 5 * 1024 * 1024) {
      alert('图片大小不能超过 5MB');
      return;
    }

    const reader = new FileReader();
    reader.onload = (ev) => {
      const result = ev.target?.result as string;
      setWallpaper(result);
      localStorage.setItem('terminal_bg_image', result);
      window.dispatchEvent(new Event('wallpaper-update'));
    };
    reader.readAsDataURL(file);
  };

  const clearWallpaper = () => {
    setWallpaper('');
    localStorage.removeItem('terminal_bg_image');
    window.dispatchEvent(new Event('wallpaper-update'));
  };

  const updateOpacity = (value: number) => {
    setOpacity(value);
    localStorage.setItem('terminal_bg_opacity', value.toString());
    window.dispatchEvent(new Event('wallpaper-update'));
  };

  return (
    <div className="pt-6 space-y-6">
      <div>
        <h3 className="text-sm font-medium text-gray-700 mb-3">终端壁纸</h3>
        <div className="flex items-center gap-4">
          <label className="w-24 h-24 rounded-xl border-2 border-dashed border-gray-300 hover:border-purple-400 transition-colors cursor-pointer flex items-center justify-center overflow-hidden">
            {wallpaper ? (
              <img src={wallpaper} className="w-full h-full object-cover" />
            ) : (
              <Upload className="w-6 h-6 text-gray-400" />
            )}
            <input type="file" accept="image/*" onChange={handleUpload} className="hidden" />
          </label>
          <div className="text-sm text-gray-500">
            <p>点击上传图片 (最大 5MB)</p>
            {wallpaper && (
              <button onClick={clearWallpaper} className="text-red-500 hover:underline mt-1">清除壁纸</button>
            )}
          </div>
        </div>
      </div>

      <div>
        <h3 className="text-sm font-medium text-gray-700 mb-3 flex justify-between">
          背景不透明度 <span className="text-purple-500">{Math.round(opacity * 100)}%</span>
        </h3>
        <input
          type="range"
          min="0"
          max="1"
          step="0.05"
          value={opacity}
          onChange={(e) => updateOpacity(parseFloat(e.target.value))}
          className="w-full accent-purple-500"
        />
      </div>
    </div>
  );
}

function AboutSection() {
  return (
    <div className="pt-6 space-y-4">
      <p className="text-gray-600">
        由于不会写解密脚本于是用 AI 搓了一个奇怪小玩意。受 CyberChef 启发，基于 Electron 和 FastAPI 构建。
      </p>
      <div className="grid grid-cols-3 gap-4 text-sm">
        <div className="p-4 bg-white/60 rounded-xl">
          <div className="text-gray-500">版本</div>
          <div className="font-medium text-gray-800">0.0.2 BETA</div>
        </div>
        <div className="p-4 bg-white/60 rounded-xl">
          <div className="text-gray-500">作者</div>
          <div className="font-medium text-gray-800">QAQ</div>
        </div>
        <div className="p-4 bg-white/60 rounded-xl">
          <div className="text-gray-500">状态</div>
          <div className="font-medium text-green-600">运行中</div>
        </div>
      </div>
    </div>
  );
}
